filepath: ""
environments:
  default:
    values:
    - versionStream/src/fake-secrets.yaml.gotmpl
    - jx-values-secret-infra.yaml
repositories:
- name: jenkins-x
  url: https://storage.googleapis.com/chartmuseum.jenkins-x.io
- name: external-secrets
  url: https://godaddy.github.io/kubernetes-external-secrets
- name: jx-labs
  url: https://storage.googleapis.com/jenkinsxio-labs-private/charts
- name: jx3
  url: https://storage.googleapis.com/jenkinsxio/charts
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
- name: banzaicloud-stable
  url: https://kubernetes-charts.banzaicloud.com
releases:
- chart: external-secrets/kubernetes-external-secrets
  version: 5.2.0
  name: kubernetes-external-secrets
  namespace: secret-infra
  values:
  - versionStream/charts/external-secrets/kubernetes-external-secrets/values.yaml.gotmpl
- chart: banzaicloud-stable/vault-operator
  version: 1.3.0
  name: vault-operator
  namespace: secret-infra
- chart: jx-labs/vault-instance
  version: 0.0.1
  name: vault-instance
  namespace: secret-infra
- chart: jx-labs/pusher-wave
  version: 1.0.0
  name: pusher-wave
  namespace: secret-infra
templates: {}
missingFileHandler: ""
